#+OPTIONS: toc:nil
#+BEGIN_EXPORT md
---
layout: post
title: "DITA the first time"
categories: documentation
---
#+END_EXPORT
   I had the fortune to work in the documentation department of a
   large corporation. And one of the pluses in such a case is that
   you get to know and learn about software solutions that would
   otherwise be difficult to use or even be aware of their
   existence. In my luck I joined in a time when things were a
   changin'. The changes, of which I was not part of, included the
   transition from writing in Framemaker and using a proprietary,
   obscure and outdated content management system, to writing in DITA
   xml, and using a proprietary CCMS, or component content management
   system. I was new then and couldn't really grasp the difference
   between CMS and CCMS. Having a linguistic background, I knew that
   small differences, however insignificant they may appear in the
   eyes of the uninitiated, could really alter the whole meaning of a
   sentence. So there was definitely a difference there, but what
   exactly this extra C entailed, I couldn't say for sure from the
   start.

   I missed the chance to get my hands dirty with Framemaker, I had
   only used this program once during my student years to author my
   diploma thesis. It was a trial version but it was all that I
   needed at the time. I had already written most of my thesis in
   Word and I had become sufficiently infuriated with the difficulty
   of properly laying out my pages. So I played a bit with Framemaker
   and I discovered a new world. Granted the environment was so
   different and I had constantly to search for options, but the
   final PDF production was a breeze, with constant results every
   time and no sudden change in page layout for no apparent reason.

   Anyway, it was a pity that I didn't get my hands dirty with
   Framemaker, that would be definitely interesting. But I did get my
   hands really dirty with DITA. And I became an immediate DITA
   convert, seeing the possibilities of this framework, and all the
   logic behind it. The fact that I joined (together with quite a few
   other new writers) at this time of change was a good and a bad
   thing. It was good, since I immediately got to work on the new
   system. But it was bad, because there was a substantial number of
   old users, used to the old "good" ways, and dreading this new DITA
   thing. Furthermore, there was an extremely large corpus of legacy
   text that was semi-automatically migrated to the new format, with
   quite a few problems there. And on top of that, I quickly found
   out that my fellow newcomers found the DITA learning curve quite
   steep.

   And this was me meeting with DITA, taking a long journey with her,
   abandoning her later for another mistress, only to abandon her yet
   again for another more able one, and finally ending back to DITA,
   but now with no support from a trusted CCMS. Can DITA survive in a
   git environment? Is DITA the only way for single sourcing and
   topic based writing? Are tags a blessing or a bane? Up or Down?
   Structure or ReStructure? So many questions, that I hope I'll be
   able to answer later.
